/* Starter fine-dining restaurants — addresses and tags only (no visits/staff). */

window.RESTAURANT_SEED_LIST = {
  id: "fine-dining-top30-v1",
  restaurants: [
    {
      name: "Aira",
      address: "Biskopsvägen 9, 115 21 Stockholm, Sweden",
      tags: ["fine-dining", "star-3", "michelin"],
      note: "3 Michelin stars",
    },
    {
      name: "Frantzén",
      address: "Klara Norra Kyrkogata 26, 111 22 Stockholm, Sweden",
      tags: ["fine-dining", "star-3", "michelin"],
      note: "3 Michelin stars",
    },
    {
      name: "Gastrologik",
      address: "Artillerigatan 14, 114 51 Stockholm, Sweden",
      tags: ["fine-dining", "star-2", "michelin"],
      note: "2 Michelin stars",
    },
    {
      name: "Nour",
      address: "Norra Stationsgatan 93, 113 53 Stockholm, Sweden",
      tags: ["fine-dining", "star-2", "michelin"],
      note: "2 Michelin stars",
    },
    {
      name: "Adam/Albin",
      address: "Radmansgatan 77, 113 60 Stockholm, Sweden",
      tags: ["fine-dining", "star-2", "michelin"],
      note: "2 Michelin stars",
    },
    {
      name: "Agrikultur",
      address: "Roslagsgatan 43, 113 54 Stockholm, Sweden",
      tags: ["fine-dining", "star-1", "michelin"],
      note: "1 Michelin star",
    },
    {
      name: "Ekstedt",
      address: "Humlegårdsgatan 17, 114 46 Stockholm, Sweden",
      tags: ["fine-dining", "star-1", "michelin"],
      note: "1 Michelin star",
    },
    {
      name: "Oaxen Krog",
      address: "Beckholmsvägen 26, 115 21 Stockholm, Sweden",
      tags: ["fine-dining", "star-1", "michelin"],
      note: "1 Michelin star",
    },
    {
      name: "Operakällaren",
      address: "Karl XII:s torg, 111 47 Stockholm, Sweden",
      tags: ["fine-dining", "star-1", "michelin", "special-occasion"],
      note: "1 Michelin star",
    },
    {
      name: "Brasserie Astoria",
      address: "Nybrogatan 15, 114 39 Stockholm, Sweden",
      tags: ["fine-dining", "michelin"],
      note: "Fine dining brasserie",
    },
    {
      name: "Copine",
      address: "Kommendörsgatan 7, 114 48 Stockholm, Sweden",
      tags: ["fine-dining", "star-1", "michelin"],
      note: "1 Michelin star",
    },
    {
      name: "Volt",
      address: "Kommendörsgatan 16, 114 48 Stockholm, Sweden",
      tags: ["fine-dining", "michelin"],
      note: "Nordic fine dining",
    },
    {
      name: "Portal",
      address: "Regeringsgatan 79, 111 39 Stockholm, Sweden",
      tags: ["fine-dining", "star-1", "michelin"],
      note: "1 Michelin star",
    },
    {
      name: "Woodstockholm",
      address: "Torsgatan 19, 113 21 Stockholm, Sweden",
      tags: ["fine-dining", "star-1", "michelin"],
      note: "1 Michelin star",
    },
    {
      name: "Växthuset",
      address: "Hammarby Slussväg 2, 118 60 Stockholm, Sweden",
      tags: ["fine-dining", "star-1", "michelin"],
      note: "1 Michelin star",
    },
    {
      name: "Celeste",
      address: "Regeringsgatan 65, 111 56 Stockholm, Sweden",
      tags: ["fine-dining", "michelin"],
      note: "Fine dining",
    },
    {
      name: "Lilla Ego",
      address: "Västmannagatan 69, 113 26 Stockholm, Sweden",
      tags: ["fine-dining", "michelin"],
      note: "Bib Gourmand",
    },
    {
      name: "Sturehof",
      address: "Stureplan 2, 114 35 Stockholm, Sweden",
      tags: ["fine-dining", "michelin", "business-lunch"],
      note: "Classic Stockholm brasserie",
    },
    {
      name: "TAK",
      address: "Brunkebergstorg 9, 111 51 Stockholm, Sweden",
      tags: ["fine-dining", "michelin"],
      note: "Nordic-Japanese fine dining",
    },
    {
      name: "Babette",
      address: "Rådmansgatan 12, 114 25 Stockholm, Sweden",
      tags: ["fine-dining", "michelin"],
      note: "Italian fine dining",
    },
    {
      name: "Hantverket",
      address: "Sturegatan 14, 114 35 Stockholm, Sweden",
      tags: ["fine-dining", "michelin"],
      note: "Nordic cuisine",
    },
    {
      name: "Gondolen",
      address: "Stadsgården 6, 116 45 Stockholm, Sweden",
      tags: ["fine-dining", "michelin", "special-occasion"],
      note: "Classic Stockholm dining",
    },
    {
      name: "Den Gyldene Freden",
      address: "Österlånggatan 51, 111 31 Stockholm, Sweden",
      tags: ["fine-dining", "michelin", "special-occasion"],
      note: "Historic Stockholm restaurant",
    },
    {
      name: "Niklas",
      address: "Högbergsgatan 53, 118 54 Stockholm, Sweden",
      tags: ["fine-dining", "michelin"],
      note: "Fine dining",
    },
    {
      name: "Esperanto",
      address: "Kungstensgatan 2, 114 25 Stockholm, Sweden",
      tags: ["fine-dining", "star-1", "michelin"],
      note: "1 Michelin star",
    },
    {
      name: "FZN Dubai",
      address: "Atlantis The Palm, Crescent Road, The Palm Jumeirah, Dubai, United Arab Emirates",
      tags: ["fine-dining", "star-2", "michelin"],
      note: "Frantzén Dubai — 2 Michelin stars",
    },
    {
      name: "Geranium",
      address: "Per Henrik Lings Allé 4, 2100 Copenhagen, Denmark",
      tags: ["fine-dining", "star-3", "michelin"],
      note: "3 Michelin stars",
    },
    {
      name: "Maaemo",
      address: "Schweigaards gate 15B, 0191 Oslo, Norway",
      tags: ["fine-dining", "star-3", "michelin"],
      note: "3 Michelin stars",
    },
    {
      name: "Jordnær",
      address: "Gentoftegade 29, 2820 Gentofte, Denmark",
      tags: ["fine-dining", "star-2", "michelin"],
      note: "2 Michelin stars",
    },
    {
      name: "Reale",
      address: "Via Carlo de Maratta 53, 00185 Rome, Italy",
      tags: ["fine-dining", "star-1", "michelin"],
      note: "1 Michelin star",
    },
  ],
};
